### ISSUE TITLE
mac 下chrome 收藏后评论没反应；

### ISSUE THREAD

**Issue by kakukeme** [cloudfavorites/favorites-web#1]
mac 下chrome 收藏后，其他人评论过，再次评论，没反应……
![dingtalk20160930170712](https://cloud.githubusercontent.com/assets/1135897/18986681/8696816c-8730-11e6-836d-a5614bd3a144.png)

**Comment by qiaorulai** [comment]
评论使用这句话：【<script >alert("好厉害“)</script>】。没反应就对了。

**Comment by ityouknow** [comment]
因为有人评论里面注入了js(**<script >alert("好厉害“)</script>**),所以有一条没显示出来，回头有时间可以优化一下这块。
