### ISSUE TITLE
你好， 咨询个问题， 你的产品开源了， 你不担心别人抄袭你的作品

### ISSUE THREAD

**Issue by javaLover1984** [cloudfavorites/favorites-web#10]
如题

**Comment by ityouknow** [comment]
哈哈哈，这个问题吗   我们只是一帮技术并没有指望这个开源产品赚钱什么的，另外我们也是来源于互联网的一个产品，如果继续往前走，功能和创新的肯定会不断。

**Comment by zhouyongtao** [comment]
我觉没有必要，估计你想多了，这么互联网公司看重的是大方向，做一个类似这样的东东分分钟。

**Comment by xiaohongwang** [comment]
学习，共同进步




At 2017-11-17 11:35:56, "纯洁的微笑" <notifications@github.com> wrote:


Closed #10.
