### ISSUE TITLE
timeout

### ISSUE THREAD

**Issue by MargeluYang** [cloudfavorites/favorites-web#111]
![image](https://user-images.githubusercontent.com/49360349/90363349-2264c600-e095-11ea-8a18-f8289780e9bb.png)
I'm fixed.
![image](https://user-images.githubusercontent.com/49360349/90363475-65269e00-e095-11ea-86ad-7edc752cbd1d.png)
and runnig succeed!
![image](https://user-images.githubusercontent.com/49360349/90363515-7e2f4f00-e095-11ea-9240-2c91893aba7f.png)
but can't acsess this ip:10.17.43.62
![image](https://user-images.githubusercontent.com/49360349/90363731-ca7a8f00-e095-11ea-81db-59a10ca8a5b1.png)
I hope you can tell me why. Thanks!

**Comment by Arisono** [comment]
1.第一步：检查你的ip地址是不是公网，能不我公网访问。
2.第二步：nginx出现502错误，错误原因是项目没有启动，项目在不断的重启当中，占用cpu100.

问题已经解决，该问题是由于配置文件缺失字段导致启动项目的时候，不断重启。导致cpu占满100%。
解决方法，我已经写了文档，有需要的可以参考一下：https://www.yundashi168.com/244.html

**Comment by pussyboy666** [comment]
> 1.第一步：检查你的ip地址是不是公网，能不我公网访问。
> 2.第二步：nginx出现502错误，错误原因是项目没有启动，项目在不断的重启当中，占用cpu100.
> 
> 问题已经解决，该问题是由于配置文件缺失字段导致启动项目的时候，不断重启。导致cpu占满100%。
> 解决方法，我已经写了文档，有需要的可以参考一下：https://www.yundashi168.com/244.html




配置文件缺失字段 是缺失哪个字段能说清楚吗

**Comment by Arisono** [comment]
仔细看我写的教程说明哦  @pussyboy666
