### ISSUE TITLE
你好，项目文件中，似乎缺少webjars的相关配置部分

### ISSUE THREAD

**Issue by xiaohaogongzuo** [cloudfavorites/favorites-web#13]
pom.xml文件中，没有找到webjars相关配置，在别的地方配置的吗？如何配置的呢？
谢谢分享

**Comment by xiaohaogongzuo** [comment]
对了，我是在maven中重新加载这个项目了，启动访问都正常，页面提示找不到 js 文件，发现没有相关webjars 部分的配置。。。

**Comment by xiaohaogongzuo** [comment]
我自己搜索了页面上的/webjars/引用，然后在pom重配置了引入，项目运行一切正常了。。。

**Comment by souvc** [comment]
我添加了支持Maven的配置，可以看下是否可以解决缺少webjars的问题。
