### ISSUE TITLE
maven 编译报错，idea工具

### ISSUE THREAD

**Issue by itapril** [cloudfavorites/favorites-web#17]
您好，刚下代码下来，maven install 报错
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:1.4.2.RELEASE:repackage (default) on project favorites-web: Execution default of goal org.springframework.boot:spring-boot-maven-plugin:1.4.2.RELEASE:repackage failed: Unable to find a single main class from the following candidates [com.favorites.Application, com.favorites.utils.Base64, com.favorites.utils.URLUtil] -> [Help 1]
还是我自己的环境有问题

**Comment by ityouknow** [comment]
我刚用最新的pom包试了一下，没有问题。应该是你本地环境的问题，请多检查吧。

**Comment by itapril** [comment]
多谢多谢，我这边已经能运行起来了。谢谢分享~~
