### ISSUE TITLE
collect表为空时异常

### ISSUE THREAD

**Issue by archerLj** [cloudfavorites/favorites-web#18]
刚clone了一份工程到本地，mysql和redis都配置过，不过全是空的，没有任何数据，访问`http://localhost:8080/index`直接卡在`CollectorRepositoryImpl`的`getMostCollectUser()`这里了，`Object[] obj =  objecArraytList.get(0);`, objecArraytList为空的时候就有问题了。不知道是否有初始的数据？

**Comment by ityouknow** [comment]
最新代码已经修复。
