### ISSUE TITLE
你好，初学Spring Boot，在学习你的开源项目，想问一下SecurityFilter中doFilter方法具体做了哪些事？

### ISSUE THREAD

**Issue by gistmap** [cloudfavorites/favorites-web#22]
另外在doFilter的最后 if (flag)处 有两段重复代码。望解惑。

**Comment by archerLj** [comment]
借用一下，`SecurityFilter`中48行的`if (containsSuffix(uri) || GreenUrlSet.contains(uri) || containsKey(uri)) {`，GreenUrISet包含了`Const.BASE_PATH`，`GreenUrISet.contains(uri)`应该一直都是false了。比如访问`http://localhost:8080/tool`并不会跳转到tool页面。另外，最后的代码确实是重复代码，IDEA会有提示的。

**Comment by xiaohongwang** [comment]
filter我还在学习，目前只是写了个简单例子



At 2017-11-17 11:35:43, "纯洁的微笑" <notifications@github.com> wrote:


Closed #22.
