### ISSUE TITLE
学习thymeleaf遇到一个问题

### ISSUE THREAD

**Issue by a846487248** [cloudfavorites/favorites-web#30]
我是在遇到问题查找时看到这个项目的，我主要是我的spring+springmvc+mybatis配置的thymeleaf模板没有生效，就是th:这样写的标签都没效果。这个项目是用springboot的。希望作者能帮我解一下问题

**Comment by ityouknow** [comment]
你什么都没有提供无法给你解决。

**Comment by a846487248** [comment]
不知道怎么回事，我重新建一个项目。再把pom文件里的东西复制过去又可以了
