### ISSUE TITLE
图片上传是怎么做的

### ISSUE THREAD

**Issue by linkebin** [cloudfavorites/favorites-web#31]
因为是内置的tomcat无法通过代码来找到相对路径。
没看懂这个配置的路径的意思。static.url = /usr/local/zx-runtime/favorites-web/apache-tomcat-8.5.4/webapps/ROOT/WEB-INF/classes/static/
不知道能不能解释一下。谢谢

**Comment by ityouknow** [comment]
这是以前使用独立tomcat部署的时候设置的路径，现在不用这个路径了。
