### ISSUE TITLE
SecurityFilter中应该是Session过期后，又重新设置成登录状态，这是什么场景需要的？

### ISSUE THREAD

**Issue by zwaizy** [cloudfavorites/favorites-web#32]
![image](https://user-images.githubusercontent.com/16435100/30465917-ce3b2c30-9a0c-11e7-8d9c-45ee10458697.png)

**Comment by ityouknow** [comment]
这块逻辑比较复杂，涉及到没有登录的用户，在收藏的时候先去登录页面，登录之后再跳转回来。
