### ISSUE TITLE
JPA创建数据带来的问题

### ISSUE THREAD

**Issue by tiamohummer** [cloudfavorites/favorites-web#34]
JPA自动创建的表时，默认编码是   ENGINE=InnoDB DEFAULT CHARSET=latin1;

导致 UserController中注册用户时，创建Favorites表时出现，incorrect string 

Favorites favorites = favoritesService.saveFavorites(user.getId(),0l, "未读列表");

这段代码中“未读列表”  与表的编码格式不符，导致插入数据不成功

从而导致后续，Favorites表， config表 创建失败

可以考虑不要让注册用户，与初始化Favorites表，config表耦合。。。

**Comment by ityouknow** [comment]
这个可能和你的本地数据库安装的默认格式有关系，我这里就没有问题。
