### ISSUE TITLE
getNoticeNum 触发调用

### ISSUE THREAD

**Issue by jianjun2015** [cloudfavorites/favorites-web#35]
这个方法[com.favorites.web.NoticeController.getNoticeNum()]每十分钟触发一次，请问是在哪里配置或者调用的呀，谢谢

**Comment by ityouknow** [comment]
这个实在也没触发的，过十分钟查找一下是否有通知提醒什么的。

**Comment by jianjun2015** [comment]
嗯，谢谢！但是我还是没明白10分钟检查一次是如何被执行的

**Comment by ityouknow** [comment]
看下主页的js
