### ISSUE TITLE
怎么获取窗口中的网站信息的？

### ISSUE THREAD

**Issue by sxbo** [cloudfavorites/favorites-web#40]
双击云收藏按钮时，在新打开的页面中获取另一个窗口中的url，title，description，charset，是怎么做到的，能解释下原理吗？

**Comment by chwwww** [comment]
点按钮执行下面这段js
`(function(){
		var description;
		var desString="";
		var metas=document.getElementsByTagName('meta');
		for(var x=0,y=metas.length;x<y;x  ){
			if(metas[x].name.toLowerCase()=="description"){
				description=metas[x];
			}
		}
		if(description){
			desString="&description=" + encodeURIComponent(description.content);
		}
		var win=window.open("http://127.0.0.1:8080/collect?from=webtool&url="
			+encodeURIComponent(document.URL)
			+desString
			+"&title="
			+encodeURIComponent(document.title)
			+"&charset="
			+document.charset,
			'_blank');
		win.focus();
	})();`

**Comment by sxbo** [comment]
知道了，谢谢
