### ISSUE TITLE
HtmlUtil.java报错   根本跑步起来啊

### ISSUE THREAD

**Issue by skyscraperxun** [cloudfavorites/favorites-web#46]
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;

以上3个类  引用的org。jsoup
jar包在  但是仍然报错啊

**Comment by skyscraperxun** [comment]
sql文件能否共享一下呢

**Comment by ityouknow** [comment]
认真看简介和已关闭问题。
