### ISSUE TITLE
收藏夹最好支持多级子目录

### ISSUE THREAD

**Issue by 1135831485** [cloudfavorites/favorites-web#5]

**Comment by Smilence1024** [comment]
后续会支持多级子目录，目前正在设计中，敬请期待。

**Comment by tao0111225** [comment]
@Smilence1024 你好，如果支持多级子目录可以通知一下吗？
感觉这个项目超级棒，谢谢开源

**Comment by tao0111225** [comment]
@Smilence1024 你好，如果支持多级子目录可以通知一下吗？
感觉这个项目超级棒，谢谢开源。
