### ISSUE TITLE
为什么不使用单cookie维持会话状态

### ISSUE THREAD

**Issue by HiroyukiSawano** [cloudfavorites/favorites-web#50]
看了一下SecurityFilter，有点疑惑，代码的意思应该是session失效或者关闭浏览器找不到session之后，使用cookie重新刷新session登录状态。但个人感觉只要cookie合法(通过校验) 就可以放行，无需更新session状态。后来看到里面有一个检验用户是否已被注销的查询校验，如果按照我的想法每次校验cookie的话，都会去查询一次数据库，难道这个刷新session只是为了减少数据库的查询？

**Comment by ityouknow** [comment]
每次登陆都需要更新 session的失效时候。
