### ISSUE TITLE
数据库

### ISSUE THREAD

**Issue by lijiangdong** [cloudfavorites/favorites-web#51]
数据库文件在哪里啊

**Comment by sintang007** [comment]
一、Redis配置
1、下载Redis
https://github.com/MicrosoftArchive/redis/releases/download/win-3.2.100/Redis-x64-3.2.100.zip
2、解压D盘，重命名为redis
3、运行CMD，进入到redis目录
4、启动redis-server
   运行命令：redis-server.exe redis.windows.conf
5、启动redis-client
   另启动一个CMD，运行命令： redis-cli.exe -h 127.0.0.1 -p 6379
6、设置Redis访问密码
   运行命令：CONFIG set requirepass "redis123"

二、Mysql设置
1、创建数据库
CREATE DATABASE `favorites` CHARACTER SET 'utf8';

三、项目application-dev.properties设置
1、设置数据库访问密码，spring.datasource.password 默认为root，根据需要修改为自己的root用户密码。
2、设置Redis服务地址，spring.redis.host改为127.0.0.1
例如：
spring.datasource.password=root
spring.redis.host=127.0.0.1

四、启动项目，运行com.favorites.Application的Main方法可以了，项目启动后数据库自动就创建好了。

**Comment by meijieman** [comment]
提供一点测试用的数据比较好
