### ISSUE TITLE
为什么登陆一直在刷新数据

### ISSUE THREAD

**Issue by renjiankl** [cloudfavorites/favorites-web#52]
Hibernate: select user0_.id as id1_12_0_, user0_.background_picture as backgrou2_12_0_, user0_.create_time as create_t3_12_0_, user0_.email as email4_12_0_, user0_.introduction as introduc5_12_0_, user0_.last_modify_time as last_mod6_12_0_, user0_.out_date as out_date7_12_0_, user0_.pass_word as pass_wor8_12_0_, user0_.profile_picture as profile_9_12_0_, user0_.user_name as user_na10_12_0_, user0_.validata_code as validat11_12_0_ from user user0_ where user0_.id=?
2017-11-28 18:15:53.923  INFO 19176 --- [nio-8888-exec-2] c.favorites.comm.filter.SecurityFilter   : userId :1
Hibernate: select user0_.id as id1_12_0_, user0_.background_picture as backgrou2_12_0_, user0_.create_time as create_t3_12_0_, user0_.email as email4_12_0_, user0_.introduction as introduc5_12_0_, user0_.last_modify_time as last_mod6_12_0_, user0_.out_date as out_date7_12_0_, user0_.pass_word as pass_wor8_12_0_, user0_.profile_picture as profile_9_12_0_, user0_.user_name as user_na10_12_0_, user0_.validata_code as validat11_12_0_ from user user0_ where user0_.id=?
2017-11-28 18:15:53.961  INFO 19176 --- [nio-8888-exec-6] c.favorites.comm.filter.SecurityFilter   : userId :1
Hibernate: select user0_.id as id1_12_0_, user0_.background_picture as backgrou2_12_0_, user0_.create_time as create_t3_12_0_, user0_.email as email4_12_0_, user0_.introduction as introduc5_12_0_, user0_.last_modify_time as last_mod6_12_0_, user0_.out_date as out_date7_12_0_, user0_.pass_word as pass_wor8_12_0_, user0_.profile_picture as profile_9_12_0_, user0_.user_name as user_na10_12_0_, user0_.validata_code as validat11_12_0_ from user user0_ where user0_.id=?
2017-11-28 18:15:54.011  INFO 19176 --- [nio-8888-exec-5] c.favorites.comm.filter.SecurityFilter   : userId :1
Hibernate: select user0_.id as id1_12_0_, user0_.background_picture as backgrou2_12_0_, user0_.create_time as create_t3_12_0_, user0_.email as email4_12_0_, user0_.introduction as introduc5_12_0_, user0_.last_modify_time as last_mod6_12_0_, user0_.out_date as out_date7_12_0_, user0_.pass_word as pass_wor8_12_0_, user0_.profile_picture as profile_9_12_0_, user0_.user_name as user_na10_12_0_, user0_.validata_code as validat11_12_0_ from user user0_ where user0_.id=?
2017-11-28 18:15:54.053  INFO 19176 --- [nio-8888-exec-1] c.favorites.comm.filter.SecurityFilter   : userId :1
Hibernate: select user0_.id as id1_12_0_, user0_.background_picture as backgrou2_12_0_, user0_.create_time as create_t3_12_0_, user0_.email as email4_12_0_, user0_.introduction as introduc5_12_0_, user0_.last_modify_time as last_mod6_12_0_, user0_.out_date as out_date7_12_0_, user0_.pass_word as pass_wor8_12_0_, user0_.profile_picture as profile_9_12_0_, user0_.user_name as user_na10_12_0_, user0_.validata_code as validat11_12_0_ from user user0_ where user0_.id=?
2017-11-28 18:15:54.096  INFO 19176 --- [nio-8888-exec-4] c.favorites.comm.filter.SecurityFilter   : userId :1
Hibernate: select user0_.id as id1_12_0_, user0_.background_picture as backgrou2_12_0_, user0_.create_time as create_t3_12_0_, user0_.email as email4_12_0_, user0_.introduction as introduc5_12_0_, user0_.last_modify_time as last_mod6_12_0_, user0_.out_date as out_date7_12_0_, user0_.pass_word as pass_wor8_12_0_, user0_.profile_picture as profile_9_12_0_, user0_.user_name as user_na10_12_0_, user0_.validata_code as validat11_12_0_ from user user0_ where user0_.id=?
2017-11-28 18:15:54.150  INFO 19176 --- [nio-8888-exec-8] c.favorites.comm.filter.SecurityFilter   : userId :1

**Comment by renjiankl** [comment]
``Hibernate: select user0_.id as id1_12_0_, user0_.background_picture as backgrou2_12_0_, user0_.create_time as create_t3_12_0_, user0_.email as email4_12_0_, user0_.introduction as introduc5_12_0_, user0_.last_modify_time as last_mod6_12_0_, user0_.out_date as out_date7_12_0_, user0_.pass_word as pass_wor8_12_0_, user0_.profile_picture as profile_9_12_0_, user0_.user_name as user_na10_12_0_, user0_.validata_code as validat11_12_0_ from user user0_ where user0_.id=?
2017-11-28 18:15:53.923  INFO 19176 --- [nio-8888-exec-2] c.favorites.comm.filter.SecurityFilter   : userId :1
Hibernate: select user0_.id as id1_12_0_, user0_.background_picture as backgrou2_12_0_, user0_.create_time as create_t3_12_0_, user0_.email as email4_12_0_, user0_.introduction as introduc5_12_0_, user0_.last_modify_time as last_mod6_12_0_, user0_.out_date as out_date7_12_0_, user0_.pass_word as pass_wor8_12_0_, user0_.profile_picture as profile_9_12_0_, user0_.user_name as user_na10_12_0_, user0_.validata_code as validat11_12_0_ from user user0_ where user0_.id=?
2017-11-28 18:15:53.961  INFO 19176 --- [nio-8888-exec-6] c.favorites.comm.filter.SecurityFilter   : userId :1
Hibernate: select user0_.id as id1_12_0_, user0_.background_picture as backgrou2_12_0_, user0_.create_time as create_t3_12_0_, user0_.email as email4_12_0_, user0_.introduction as introduc5_12_0_, user0_.last_modify_time as last_mod6_12_0_, user0_.out_date as out_date7_12_0_, user0_.pass_word as pass_wor8_12_0_, user0_.profile_picture as profile_9_12_0_, user0_.user_name as user_na10_12_0_, user0_.validata_code as validat11_12_0_ from user user0_ where user0_.id=?
2017-11-28 18:15:54.011  INFO 19176 --- [nio-8888-exec-5] c.favorites.comm.filter.SecurityFilter   : userId :1
Hibernate: select user0_.id as id1_12_0_, user0_.background_picture as backgrou2_12_0_, user0_.create_time as create_t3_12_0_, user0_.email as email4_12_0_, user0_.introduction as introduc5_12_0_, user0_.last_modify_time as last_mod6_12_0_, user0_.out_date as out_date7_12_0_, user0_.pass_word as pass_wor8_12_0_, user0_.profile_picture as profile_9_12_0_, user0_.user_name as user_na10_12_0_, user0_.validata_code as validat11_12_0_ from user user0_ where user0_.id=?
2017-11-28 18:15:54.053  INFO 19176 --- [nio-8888-exec-1] c.favorites.comm.filter.SecurityFilter   : userId :1
Hibernate: select user0_.id as id1_12_0_, user0_.background_picture as backgrou2_12_0_, user0_.create_time as create_t3_12_0_, user0_.email as email4_12_0_, user0_.introduction as introduc5_12_0_, user0_.last_modify_time as last_mod6_12_0_, user0_.out_date as out_date7_12_0_, user0_.pass_word as pass_wor8_12_0_, user0_.profile_picture as profile_9_12_0_, user0_.user_name as user_na10_12_0_, user0_.validata_code as validat11_12_0_ from user user0_ where user0_.id=?
2017-11-28 18:15:54.096  INFO 19176 --- [nio-8888-exec-4] c.favorites.comm.filter.SecurityFilter   : userId :1
Hibernate: select user0_.id as id1_12_0_, user0_.background_picture as backgrou2_12_0_, user0_.create_time as create_t3_12_0_, user0_.email as email4_12_0_, user0_.introduction as introduc5_12_0_, user0_.last_modify_time as last_mod6_12_0_, user0_.out_date as out_date7_12_0_, user0_.pass_word as pass_wor8_12_0_, user0_.profile_picture as profile_9_12_0_, user0_.user_name as user_na10_12_0_, user0_.validata_code as validat11_12_0_ from user user0_ where user0_.id=?
2017-11-28 18:15:54.150  INFO 19176 --- [nio-8888-exec-8] c.favorites.comm.filter.SecurityFilter   : userId :1

**Comment by ityouknow** [comment]
获取用户的点赞 消息等定时任务。
