### ISSUE TITLE
问一下如何配置才能让所有的unit test通过

### ISSUE THREAD

**Issue by SzLizarrrr** [cloudfavorites/favorites-web#55]
我在application-dev.properties里添加了自己的dataSource和redis。项目成功跑起来啦，非常好的项目谢谢~！
就是我现在想把unit test也能跑一遍，但是都报 java.lang.IllegalStateException: Failed to load ApplicationContext。
请问一下unit test那边需要配置些什么？？？

**Comment by ityouknow** [comment]
这个需要先单独将每个test调通，当时只是跑单元的测试。
