### ISSUE TITLE
大哥们，你们不要倒闭好吗？再坚持一会。

### ISSUE THREAD

**Issue by zdylalala** [cloudfavorites/favorites-web#57]
大哥们，拜托了，不要倒闭，我里面收藏了好多东西。。12.8号后台坏了，麻烦修好一下，我把东西全部转出来。。我不用了还不行吗？？大哥们，谢谢了，赶紧修好一会。我马上把东西全部转出来。。

**Comment by ityouknow** [comment]
@zdylalala  放心 不会倒闭的，我会一直运营下去。昨天调整了程序

**Comment by ityouknow** [comment]
再试一下。

**Comment by zdylalala** [comment]
实言相告:已经转出。转到了  印象笔记 了。。https://www.yinxiang.com/  大牌还是靠谱点。Sorry..

**Comment by ityouknow** [comment]
@zdylalala 让我很尴尬，不过也欢迎你常回来转转，我承若不会让我们的用户有数据丢失的风险，虽然我们只是一个开源的项目，但是还是会努力的运营下去。

**Comment by mbldlkk** [comment]
我不用了还不行吗？<滑稽>
