### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by wujisheng** [cloudfavorites/favorites-web#6]
两个问题：
一：为什么SecurityFilter.java 在登陆的时候默认要跳到index页面，跳转到login不好吗？新程序的话跳转到index页面会报错；
二：怎么设置日志的编码格式呢？我的控制台中的日志输出是乱码，猜测是日志输出是gbk的，但是favorite-web.log文件中的日志显示却正常？

**Comment by Smilence1024** [comment]
@wujisheng 问题一：如果没登录直接访问会进入首页（index），不会直接跳到登陆页面，因为首页有介绍的内容和登陆入口。“新程序跳到index页面会报错”中的新程序指的是什么？
问题二：日志输出是UTF-8编码，控制台中的日志乱码应该调试开发工具的编码格式

**Comment by wujisheng** [comment]
问题一：访问index页面会执行到CollectorRepositoryImpl.getMostCollectUser()方法，该方法中：Object[] obj =  objecArraytList.get(0);，但是这时候数据库中没有任何数据，objecArraytList.get(0)会报错。

**Comment by Smilence1024** [comment]
@wujisheng 这确实是个问题，因为首页这个需求是后续增加的，忽略了数据库中数据特别少或者没有的情况，我们尽快修复，非常感谢

**Comment by wujisheng** [comment]
@Smilence1024 没有，没有，该我谢谢你们，最近正好想学习spring boot，看到你们的这个开源项目，感觉不错，非常感谢。
