### ISSUE TITLE
spring-session移除

### ISSUE THREAD

**Issue by it-noob** [cloudfavorites/favorites-web#60]
微笑哥，spring-session是因为什么原因移除了呢？

**Comment by ityouknow** [comment]
使用的最低配置服务器，再开一个redis比较耗子资源，就先关了。

**Comment by it-noob** [comment]
好的，看您的springboot和springcloud系列在写东西，但是感觉springboot的工程，没有涉及权限整合这块儿。比如spring-session和shiro做整合，权限处理等；以及springcloud的一个类似于favorites-web的开源工程有计划做么？

**Comment by ityouknow** [comment]
spring-session和shiro 分别的文章都有了，SpirngCloud貌似现在没有，大家可以提提建议，我找人员一起做一个也没有问题。

**Comment by it-noob** [comment]
微笑哥，感觉您看github比小密圈频繁些，之前有跟人讨论spring-session的使用问题，比如spring-session占用空间大，针对一个session记录创建3个key，分别一个set一个hash一个string。您是怎么看待的，或者您在实践过程中，是怎么处理session登录的。因为本工程里的登录只是自定义的filter。如果跟shiro集成，我发现session用的是shiro的session，并不是spring-session的session。这就导致我启动两个实例，访问实例A做认证登录后，访问实例B还需要重新认证登录。
