### ISSUE TITLE
我得跑起来了，请问，我只是建个库，是什么create table的

### ISSUE THREAD

**Issue by zljxh** [cloudfavorites/favorites-web#62]

**Comment by zljxh** [comment]
或者说那里做了配置。ps 感谢@纯洁的微笑。

**Comment by SzLizarrrr** [comment]
据我肤浅的了解，spring data jpa是自己会根据对应的数据库里去找有没有符合名字的表格。如果没有就会自己建表的。所以如果你说什么地方做了create table，可能spring根据domain包里的各种@Entity, @Id等等自动生成了表格。

**Comment by ityouknow** [comment]
只需要自己建库
