### ISSUE TITLE
使用idea导入报错 是不是我包的版本问题？

### ISSUE THREAD

**Issue by CTLifeHand** [cloudfavorites/favorites-web#77]
Error:(133, 48) java: 找不到符号   符号:   方法 of(java.lang.Integer,java.lang.Integer,org.springframework.data.domain.Sort)   位置: 类 org.springframework.data.domain.PageRequest

**Comment by notOnly20k** [comment]
请问你这个情况解决了吗？我也是这个包报错
Error:(58, 44) java: 找不到符号
  符号:   方法 of(java.lang.Integer,java.lang.Integer,org.springframework.data.domain.Sort)
  位置: 类 org.springframework.data.domain.PageRequest

**Comment by dragonge** [comment]
springboot版本问题
