### ISSUE TITLE
这个项目有没有maven版本的？

### ISSUE THREAD

**Issue by liubo988** [cloudfavorites/favorites-web#8]
你好，我想搞个maven的 ，你们这个项目有maven版本的吗?

**Comment by ityouknow** [comment]
暂时没有maven版本的其实只要，将gradle配置信息改一下就成maven版本了。

**Comment by souvc** [comment]
已经推送Maven版本的支持，看作者是否合并了。

**Comment by ityouknow** [comment]
已经合并，感谢 @souvc
