### ISSUE TITLE
增强对JDK10环境对兼容性

### ISSUE THREAD

**Issue by linkerlin** [cloudfavorites/favorites-web#86]
我会提几个PR。
都记录在这里。

**Comment by linkerlin** [comment]
#87 MySQL8和JDK10支持

**Comment by ityouknow** [comment]
@linkerlin 好，感谢。

**Comment by linkerlin** [comment]
#88 修改了mysql连接串，增加了hibernate的配置

**Comment by linkerlin** [comment]
MySQL8：
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

**Comment by linkerlin** [comment]
@ityouknow 请审阅 #88 #87

**Comment by my13901** [comment]
@linkerlin 多谢你的代码。我就说 为啥数据库一直连不上。原来用了mysql8.
